session_name: NixOpenSpec
windows:
  - window_name: NixOpenSpec
    layout: main-vertical
    options:
      main-pane-width: 20%
    panes:
      - shell_command:
          - cd ~/Documents/Notes/Projects/nix-openspec
          # - nvim Notes.md ToDo.md
          - open-project
      - shell_command:
          - tmux resizep -y 85%
          - filelist-open "startup_files.txt" nix-openspec
        focus: true
      - clear
